AWSTemplateFormatVersion: 2010-09-09
Description: s3apt repository


Outputs:
  DomainName:
    Value: !Ref DomainName
    Export:
      Name: !Sub '${AWS::StackName}-DomainName'
  BucketArn:
    Value: !GetAtt AptBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-BucketArn'
  BucketDomainName:
    Value: !GetAtt AptBucket.DomainName
    Export:
      Name: !Sub '${AWS::StackName}-BucketDomainName'


Parameters:
  DomainName:
    Description: The (sub)domain that you want to use for your APT repository (e.g. apt.yourcompany.com)
    Type: String


Resources:
  AptBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        !Ref DomainName
      WebsiteConfiguration:
        IndexDocument: index.html
